// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6A_NqGuhrJBakFenyYtlqAlNNexd4Asw',
    appId: '1:862568683445:web:19103ccb09c30002596bfc',
    messagingSenderId: '862568683445',
    projectId: 'kashyabgroup',
    authDomain: 'kashyabgroup.firebaseapp.com',
    databaseURL: 'https://kashyabgroup.firebaseio.com',
    storageBucket: 'kashyabgroup.appspot.com',
    measurementId: 'G-947MV3HG1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6cojD1J1RQEZ83643g52ZgX3lnD8TH0',
    appId: '1:862568683445:android:a1fdde2838f63fa1596bfc',
    messagingSenderId: '862568683445',
    projectId: 'kashyabgroup',
    databaseURL: 'https://kashyabgroup.firebaseio.com',
    storageBucket: 'kashyabgroup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJXS-nXLFBABB4oG-8V_nhEB44Zi3S22I',
    appId: '1:862568683445:ios:cc3aa15ea6c1cf24596bfc',
    messagingSenderId: '862568683445',
    projectId: 'kashyabgroup',
    databaseURL: 'https://kashyabgroup.firebaseio.com',
    storageBucket: 'kashyabgroup.appspot.com',
    iosClientId: '862568683445-63aopo4bob2o0sr4pcodc6srvrtupscb.apps.googleusercontent.com',
    iosBundleId: 'com.dipak.todo.todo',
  );
}
